### ISSUE TITLE
can we make the version 3.0.35  work with ionic 2.2.1 ? if not is there any work around?

### ISSUE THREAD

**Issue by bhupathibhargva** [manateeworks/phonegap-manateeworks-v3#14]

**Comment by ghost** [comment]
Hi @bhupathibhargva ,

The Manatee Works Barcode Scanner phonegap plugin version 3.0.35 should work with any version of Ionic.

A few days back there was a broken dependency that prevented our plugin from being added, which has since been removed, so the plugin should be added without any problems and mwbScanner should be defined.

The only other thing we changed was the documentation for implementing our plugin in Ionic, as well as the Ionic demo app.

The latest Ionic version 3.6.0 uses different commands for creating Ionic projects than version 2.2.1.
You could still use 2.2.1, but I suggest you switch to the latest version, as the Ionic team make changes often, and the previous versions are removed from documentation and thus harder to develop for.

Regards,
Team Manatee

**Comment by bhupathibhargva** [comment]
Thank you for clarification.
