### ISSUE TITLE
Manteeworks barcode scanner crash on Windows 10

### ISSUE THREAD

**Issue by tbson** [manateeworks/phonegap-manateeworks-v3#19]
I'm using Windows 10 Version 1709 (OS Build 16299.19).
Manteeworks barcode scanner closed after I star scan a moment.
I got JS error message:
```
 "Error: WinRTError: The request is invalid in the current state.\r\nThe request is invalid in the current state."
   at Anonymous function (ms-appx://1234564556643.myapp/www/components/registration/RegistrationCtrl.js:305:17)
   at Anonymous function (ms-appx://1234564556643.myapp/www/plugins/manateeworks-barcodescanner-v3/www/MWBScanner.js:951:13)
   at Anonymous function (ms-appx://1234564556643.myapp/www/plugins/manateeworks-barcodescanner-v3/www/MWBScanner.js:572:46)
   at cordova.callbackFromNative (ms-appx://1234564556643.myapp/www/cordova.js:295:21)
   at cordova.callbackError (ms-appx://1234564556643.myapp/www/cordova.js:282:9)
   at onError (ms-appx://1234564556643.myapp/www/cordova.js:1048:17)
   at Anonymous function (ms-appx://1234564556643.myapp/www/plugins/manateeworks-barcodescanner-v3/src/windows/MWBarcodeScannerProxy.js:1385:13)
   at ErrorPromise_done (ms-appx://1234564556643.myapp/www/WinJS/js/base.js:2318:25)
```

And Windows log

```
The machine-default permission settings do not grant Local Activation permission for the COM Server application with CLSID
{C2F03A33-21F5-47FA-B4BB-156362A2F239}
 and APPID
{316CDED5-E4AE-4B15-9113-7055D84DCC97}
 to the user DESKTOP-CHNCD1L\tbson SID (S-1-5-21-3268230523-2733011267-3488820548-1001) from address LocalHost (Using LRPC) running in the application container 1234564556643.myapp_1.0.30.0_x86__h35559jr9hy9m SID (S-1-15-2-27029379-1597962913-2365468229-3442621348-1777524651-2856746473-2594178817). This security permission can be modified using the Component Services administrative tool.
```
How can I fix this issue?

**Comment by ghost** [comment]
Hi @tbson ,
We still don't have the Fall Creators Update 1709 on our Windows 10 devices so we are unable to test until we do because of [this issue](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/601d9974-b184-4a36-a877-8a07d6787a94/uwpjs-all-javascript-apps-using-camera-preview-will-crash-after-latest-windows-update?forum=wpdevelop).

We can proceed once we have the update.

Regards,
Team Manatee

**Comment by tbson** [comment]
Hello team Manatee,

After I upgraded to Fall Creators Update 1709, Your barcode scanner didn’t
cause my app crash any more (still crashed after that).

This case is just barcode scanner auto close (my app not crash) with error
I provided.

Wish you can test it soon.

Thank you

Son Tran

On 02/11/2017 at 15:10:48, Manatee Works (notifications@github.com) wrote:

Hi @tbson <https://github.com/tbson> ,
We still don't have the Fall Creators Update 1709 on our Windows 10 devices
so we are unable to test until we do because of this issue
<https://social.msdn.microsoft.com/Forums/windowsapps/en-US/601d9974-b184-4a36-a877-8a07d6787a94/uwpjs-all-javascript-apps-using-camera-preview-will-crash-after-latest-windows-update?forum=wpdevelop>
.

We can proceed once we have the update.

Regards,
Team Manatee

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/manateeworks/phonegap-manateeworks-v3/issues/19#issuecomment-341346460>,
or mute the thread

**Comment by ghost** [comment]
Hello again @tbson ,

We were able to get our desktop computers updated to 1709 16299.19 and running the application locally doesn't show any of the problems you've encountered. The barcodes are scanned rather fast (which should be the case with desktop/faster computers), the result is shown, and all the controls work as they should.

There is another problem that happens when you scan for a longer period (without a successful scan or closing the scanner) but in that case your app would stop being responsive.

Our mobile devices don't have the 16299.19 update (only 15254.1), without which update the scanner won't run.

Regards,
Team Manatee
