### ISSUE TITLE
Slow response of close preview button on Windows 10

### ISSUE THREAD

**Issue by tbson** [manateeworks/phonegap-manateeworks-v3#21]
It take several seconds to close preview if I don't want to scan any more (Click on blue button).
![close-button](https://user-images.githubusercontent.com/5618568/32482603-021053b8-c3cb-11e7-8034-8cd87484662d.jpg)

**Comment by ghost** [comment]
Hi @tbson ,

As posted on the [previous issue](https://github.com/manateeworks/phonegap-manateeworks-v3/issues/19) with the latest update 1709 build 16299.19 the plugin runs without any problems.
There is another problem that happens when you scan for a longer period (without a successful scan or closing the scanner) but in that case your app would completely stop being responsive, not become slower.

It is possible that the scanner is using up all the CPU Cores which if your machine has slow Core performance (time it takes to decode 1 frame), after closing the preview there could still be a few frames being decoded (decoder can't be stopped in mid-work, so all threads have to finish) and causing your app to be slow. 

Decoding multiple frames might be even slower if your machine uses hyper-threading for example. You can reduce the performance needed by the decoder with these [instructions](https://github.com/manateeworks/phonegap-manateeworks-v3#performance).

Best regards,
Team Manatee
