### ISSUE TITLE
Scanning not returning any value

### ISSUE THREAD

**Issue by deonvisser** [manateeworks/phonegap-manateeworks-v3#24]
Hi
Scanning initiated. Barcode detected and scanned but no value returned.

mwbScanner.startScanning(function(result){
   alert(result); //returns [object Object]
});

alert(obj.result); //Does not return anything.
License key is in and correct and all barcode types are selected in the Manatee console.

**Comment by ghost** [comment]
Hi

I see that you already opened a ticket #1743 in ManateeWorks official site so the conversation will continue there

Regards,

**Comment by princeandrewdiana** [comment]
Same problem here.

**Comment by ghost** [comment]
Hi
Of course you will have an object in the result because you have   alert(result);  so the result will be an object, so please just replace it with   alert(result.code);

Also see the code below for more information:
`/**
  * result.code - string representation of barcode result
  * result.type - type of barcode detected or 'Cancel' if scanning is canceled
  * result.bytes - bytes array of raw barcode result
  * result.isGS1 - (boolean) barcode is GS1 compliant
  * result.location - contains rectangle points p1,p2,p3,p4 with the corresponding x,y
  * result.imageWidth - Width of the scanned image
  * result.imageHeight - Height of the scanned image
  */`
Reagrds,
