### ISSUE TITLE
Barcode Scanning Overlay fails to open on Android 11

### ISSUE THREAD

**Issue by tenglandct** [manateeworks/phonegap-manateeworks-v3#29]
Hi,

This plugin does not appear to work on Android 11.

Calling the startScanning method launches the scanner activity but the user is just left with a black screen. The user is able to quit back to the app by using the back button and continue using the app without any issue but the scanning functionality simply does not function.

This has been reported by a customer using Samsung S20 and also I have replicated using Browserstack and Android 11 devices available there.

Initially I noticed logcat info around missing the SYSTEM_ALERT_WINDOW permission (which is a change in Android 11), but having manually added a uses-permission for this to the Android Manifest through the config.xml, the behaviour is the same but there no longer a warning (i.e. I believe the permission has been applied correctly but has not had the desired result)

Regards

**Comment by LazarIlievski** [comment]
HI @tenglandct 
Thank you for contacting the Customer Service Department.
Most probably starting from android 11, orientation as configChages is not working and instead of that, we need to use screenSize|screenLayout.

This is a recommendation from an android a long time ago, but up until android 11, it was still working.

However in your application open AndroidManifest.xml and make this change to ScannerActivity
![support_Screenshot_110](https://user-images.githubusercontent.com/52234330/104185692-983b4680-5415-11eb-8aaa-ef76ef744af1.png)

Regards,

**Comment by LazarIlievski** [comment]
We just released a new version phonegap-manateeworks-v3 3.1.4 and the issue is resolved. Please make a test with the new release and if everything is fine please close the issue.


Regards,

**Comment by tenglandct** [comment]
Great! Thanks Lazar, I will test now

**Comment by tenglandct** [comment]
Hi guys, confirmed working on some test devices that we have - many thanks!
